apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: http-reply-knative
  namespace: fosdem24
spec:
  template:
    spec:
      runtimeClassName: urunc
      containers:
        - image: harbor.nbfc.io/nubificus/httpreply-unikraft:latest
          env:
            - name: TARGET
              value: "Go Sample v1"